export const styles = {
  page: {
    position: "fixed",
    inset: 0, // top/right/bottom/left = 0
    display: "grid",
    placeItems: "center",
    padding: 20,
    background: "linear-gradient(180deg, #fff 0%, #fff5ec 100%)",
    fontFamily:
      'system-ui, -apple-system, Segoe UI, Roboto, "Noto Sans KR", sans-serif',
  } as const,
  card: {
    width: "100%",
    maxWidth: 420,
    background: "#fff",
    border: "1px solid #eee",
    borderRadius: 16,
    boxShadow: "0 10px 30px rgba(231, 155, 119, 0.06)",
    padding: 22,
  } as const,
  header: { textAlign: "center", marginBottom: 16 } as const,
  logo: { fontSize: 40, lineHeight: "40px" } as const,
  title: { margin: "8px 0 4px", fontSize: 22,color: "#100000"} as const,
  sub: { margin: 0, color: "#666", fontSize: 14 } as const,
  form: { display: "grid", gap: 12, marginTop: 14 } as const,
  label: { display: "grid", gap: 6, fontSize: 14, color: "#333" } as const,
  input: {
  height: 44,
  borderRadius: 10,
  border: "1px solid #ddd",
  padding: "0 12px",
  outline: "none",
  fontSize: 14,

  background: "#ffffff",   // ✅ 입력칸 배경색
  color: "#111111",        // ✅ 입력 텍스트 색
} as const,
  button: {
    height: 46,
    borderRadius: 12,
    border: "none",
    background: "#ff7a00",
    color: "white",
    fontWeight: 700,
    cursor: "pointer",
    marginTop: 4,
  } as const,
  error: {
    background: "#fff0f0",
    border: "1px solid #ffd1d1",
    color: "#b00020",
    padding: 10,
    borderRadius: 10,
    fontSize: 13,
  } as const,
  ok: {
    background: "#eefaf1",
    border: "1px solid #c9f1d2",
    color: "#0f6b2f",
    padding: 10,
    borderRadius: 10,
    fontSize: 13,
  } as const,
  hint: { fontSize: 12, color: "#888" } as const,
  footer: { marginTop: 14, fontSize: 14, color: "#444", textAlign: "center" } as const,
  link: { color: "#ff7a00", fontWeight: 700, textDecoration: "none" } as const,
  inlineBtn: {
    marginLeft: 8,
    border: "none",
    background: "transparent",
    color: "#ff7a00",
    fontWeight: 800,
    cursor: "pointer",
    padding: 0,
  } as const,
};
